In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel("Airline_Flight_and_Passenger_Analysis_Excel_Cleaned.xlsx")

In [2]:
df.shape

(34938, 25)

In [3]:
df.head()

,Passenger_ID,Flight_ID,Booking_ID,Airline,Flight_Number,Origin_Airport,Destination_Airport,Origin_City,Destination_City,Flight_Date,...,Travel_Class,Passenger_Age,Passenger_Gender,Ticket_Fare,Booking_Channel,Baggage_KG,Delay_Minutes,Cancellation_Status,Passenger_Satisfaction,Flight_Status
0,P119624,FL8581,BK1019624,SpiceJet,AI851,PNQ,DEL,Pune,Delhi,2025-10-29,...,Economy,44.0,Female,1800,Travel Agent,2.0,0,Not Cancelled,4.0,On Time
1,P128171,FL5177,BK1028171,IndiGo,G8343,HYD,CCU,Hyderabad,Kolkata,2025-01-02,...,Economy,30.0,Male,1800,Website,20.6,11,Not Cancelled,4.0,On Time
2,P101265,FL2802,BK1001265,IndiGo,AI551,MAA,DEL,Chennai,Delhi,2025-09-21,...,Business,18.0,Female,1800,Mobile App,21.7,0,Not Cancelled,4.0,On Time
3,P113536,FL7980,BK1013536,SpiceJet,QP687,HYD,DEL,Hyderabad,Delhi,2025-10-22,...,Economy,55.0,Male,1800,Website,5.7,0,Not Cancelled,4.0,On Time
4,P110869,FL3641,BK1010869,IndiGo,QP865,HYD,MAA,Hyderabad,Chennai,2025-05-08,...,Business,26.0,Female,1800,Mobile App,21.2,0,Not Cancelled,4.0,On Time

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 34938 entries, 0 to 34937
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Passenger_ID            34938 non-null  str
 1   Flight_ID               34938 non-null  str
 2   Booking_ID              34938 non-null  str
 3   Airline                 34938 non-null  str
 4   Flight_Number           34938 non-null  str
 5   Origin_Airport          34938 non-null  str
 6   Destination_Airport     34938 non-null  str
 7   Origin_City             34938 non-null  str
 8   Destination_City        34938 non-null  str
 9   Flight_Date             34938 non-null  datetime64[us]
 10  Departure_Time          34938 non-null  str
 11  Arrival_Time            34938 non-null  str
 12  Flight_Duration_Min     34938 non-null  int64
 13  Distance_KM             34938 non-null  int64
 14  Aircraft_Type           34938 non-null  str
 15  Travel_Class            34938 non-null  str
 16  Passenger_Age           34518 non-null  float64
 17  Passenger_Gender        34938 non-null  str
 18  Ticket_Fare             34588 non-null  object
 19  Booking_Channel         34938 non-null  str
 20  Baggage_KG              34308 non-null  float64
 21  Delay_Minutes           34938 non-null  object
 22  Cancellation_Status     34938 non-null  str
 23  Passenger_Satisfaction  34519 non-null  float64
 24  Flight_Status           34938 non-null  str
dtypes: datetime64[us](1), float64(3), int64(2), object(2), str(17)
memory usage: 6.7+ MB

In [6]:
df.isnull().sum().sort_values(ascending=False)

Baggage_KG                630
Passenger_Age             420
Passenger_Satisfaction    419
Ticket_Fare               350
Flight_Number               0
Flight_ID                   0
Booking_ID                  0
Airline                     0
Passenger_ID                0
Destination_City            0
Origin_City                 0
Destination_Airport         0
Origin_Airport              0
Flight_Duration_Min         0
Flight_Date                 0
Arrival_Time                0
Departure_Time              0
Travel_Class                0
Aircraft_Type               0
Distance_KM                 0
Passenger_Gender            0
Booking_Channel             0
Delay_Minutes               0
Cancellation_Status         0
Flight_Status               0
dtype: int64

In [9]:
df["Passenger_Age"] = df["Passenger_Age"].fillna(df["Passenger_Age"].median())

In [14]:
df["Ticket_Fare"].dropna().astype(str).str.contains(r"[₹,$]|,").sum()

np.int64(80)

In [15]:
df["Ticket_Fare"] = (
    df["Ticket_Fare"]
    .astype(str)
    .str.replace(r"[₹$,]", "", regex=True)
    .str.replace(",", "", regex=False)
)

In [19]:
df["Ticket_Fare"] = df["Ticket_Fare"].fillna(df["Ticket_Fare"].median())

In [22]:
df["Baggage_KG"] = df["Baggage_KG"].fillna(df["Baggage_KG"].median())

In [25]:
df["Passenger_Satisfaction"] = df["Passenger_Satisfaction"].fillna(
    df["Passenger_Satisfaction"].median()
)

In [27]:
df.isnull().sum().sort_values(ascending=False)

Passenger_ID              0
Flight_ID                 0
Booking_ID                0
Airline                   0
Flight_Number             0
Origin_Airport            0
Destination_Airport       0
Origin_City               0
Destination_City          0
Flight_Date               0
Departure_Time            0
Arrival_Time              0
Flight_Duration_Min       0
Distance_KM               0
Aircraft_Type             0
Travel_Class              0
Passenger_Age             0
Passenger_Gender          0
Ticket_Fare               0
Booking_Channel           0
Baggage_KG                0
Delay_Minutes             0
Cancellation_Status       0
Passenger_Satisfaction    0
Flight_Status             0
dtype: int64

In [28]:
df.dtypes

Passenger_ID                         str
Flight_ID                            str
Booking_ID                           str
Airline                              str
Flight_Number                        str
Origin_Airport                       str
Destination_Airport                  str
Origin_City                          str
Destination_City                     str
Flight_Date               datetime64[us]
Departure_Time                       str
Arrival_Time                         str
Flight_Duration_Min                int64
Distance_KM                        int64
Aircraft_Type                        str
Travel_Class                         str
Passenger_Age                    float64
Passenger_Gender                     str
Ticket_Fare                      float64
Booking_Channel                      str
Baggage_KG                       float64
Delay_Minutes                     object
Cancellation_Status                  str
Passenger_Satisfaction           float64
Flight_Status                        str
dtype: object

In [29]:
df["Passenger_Age"] = df["Passenger_Age"].astype(int)
df["Passenger_Satisfaction"] = df["Passenger_Satisfaction"].astype(int)

In [32]:
df["Delay_Minutes"].astype(str).str.contains("min", case=False).sum()

np.int64(25)

In [33]:
df["Delay_Minutes"] = (
    df["Delay_Minutes"]
    .astype(str)
    .str.replace("min", "", case=False, regex=False)
    .str.strip()
)

df["Delay_Minutes"] = pd.to_numeric(df["Delay_Minutes"], errors="coerce")

In [35]:
df.dtypes

Passenger_ID                         str
Flight_ID                            str
Booking_ID                           str
Airline                              str
Flight_Number                        str
Origin_Airport                       str
Destination_Airport                  str
Origin_City                          str
Destination_City                     str
Flight_Date               datetime64[us]
Departure_Time                       str
Arrival_Time                         str
Flight_Duration_Min                int64
Distance_KM                        int64
Aircraft_Type                        str
Travel_Class                         str
Passenger_Age                      int64
Passenger_Gender                     str
Ticket_Fare                      float64
Booking_Channel                      str
Baggage_KG                       float64
Delay_Minutes                      int64
Cancellation_Status                  str
Passenger_Satisfaction             int64
Flight_Status                        str
dtype: object

In [37]:
df.duplicated().sum()

np.int64(3)

In [38]:
df = df.drop_duplicates()

In [40]:
df.shape

(34935, 25)

In [41]:
df.to_excel("Airline_Flight_and_Passenger_Python_Cleaned.xlsx", index=False)

In [42]:
total_passengers = df["Passenger_ID"].nunique()
total_flights = df["Flight_ID"].nunique()
total_revenue = df["Ticket_Fare"].sum()
avg_fare = df["Ticket_Fare"].mean()
avg_delay = df["Delay_Minutes"].mean()

total_passengers, total_flights, total_revenue, avg_fare, avg_delay

(34930,
 8825,
 np.float64(62883106.0),
 np.float64(1800.0030342063833),
 np.float64(5.4480606841276655))

In [44]:
df["Airline"] = df["Airline"].str.strip().str.title()

In [46]:
df["Airline"] = df["Airline"].replace({
    "Indigo": "IndiGo",
    "Spicejet": "SpiceJet"
})

In [47]:
airline_analysis = df.groupby("Airline").agg(
    Passengers=("Passenger_ID", "nunique"),
    Flights=("Flight_ID", "nunique"),
    Revenue=("Ticket_Fare", "sum"),
    Avg_Fare=("Ticket_Fare", "mean"),
    Avg_Delay=("Delay_Minutes", "mean")
).sort_values("Passengers", ascending=False)

airline_analysis

           Passengers  Flights     Revenue     Avg_Fare  Avg_Delay
Airline
IndiGo          11851     6596  21331906.0  1800.008944   5.399544
Air India        7069     4911  12729600.0  1800.000000   5.490667
Vistara          5638     4153  10150200.0  1800.000000   5.368328
SpiceJet         4449     3496   8008200.0  1800.000000   5.382558
Go First         3176     2683   5718600.0  1800.000000   5.438464
Akasa Air        2747     2394   4944600.0  1800.000000   5.828540

In [48]:
df["Flight_Status"].value_counts()

Flight_Status
On Time      28240
Delayed       5182
Cancelled     1513
Name: count, dtype: int64

In [49]:
df["Cancellation_Status"].value_counts()

Cancellation_Status
Not Cancelled    33422
Cancelled         1513
Name: count, dtype: int64

In [51]:
df["Travel_Class"] = df["Travel_Class"].str.strip().str.title()

In [52]:
df["Travel_Class"].value_counts()

Travel_Class
Economy     26453
Business     7162
First        1320
Name: count, dtype: int64

In [54]:
df["Booking_Channel"] = df["Booking_Channel"].str.strip().str.title()

In [55]:
df["Booking_Channel"].value_counts()

Booking_Channel
Website            11759
Mobile App         10503
Travel Agent        5848
Airport Counter     3428
Corporate           3187
Unknown              210
Name: count, dtype: int64

In [56]:
df["Passenger_Gender"].value_counts()

Passenger_Gender
Male      19648
Female    14597
Other       690
Name: count, dtype: int64

In [57]:
df["Aircraft_Type"].value_counts()

Aircraft_Type
Airbus A320    11895
Boeing 737     10650
Airbus A321     6135
Boeing 787      3498
Airbus A350     2757
Name: count, dtype: int64

In [58]:
df["Passenger_Age"].describe()

count    34935.000000
mean        44.013940
std         15.258204
min         18.000000
25%         31.000000
50%         44.000000
75%         57.000000
max         70.000000
Name: Passenger_Age, dtype: float64

In [59]:
travel_class_analysis = df.groupby("Travel_Class").agg(
    Passengers=("Passenger_ID", "nunique"),
    Revenue=("Ticket_Fare", "sum"),
    Avg_Fare=("Ticket_Fare", "mean")
).sort_values("Revenue", ascending=False)

travel_class_analysis

              Passengers     Revenue     Avg_Fare
Travel_Class
Economy            26450  47615400.0  1800.000000
Business            7160  12891600.0  1800.000000
First               1320   2376106.0  1800.080303

In [60]:
delay_by_airline = df.groupby("Airline").agg(
    Avg_Delay=("Delay_Minutes", "mean"),
    Max_Delay=("Delay_Minutes", "max")
).sort_values("Avg_Delay", ascending=False)

delay_by_airline

           Avg_Delay  Max_Delay
Airline
Akasa Air   5.828540        102
Air India   5.490667         81
Go First    5.438464         97
IndiGo      5.399544         93
SpiceJet    5.382558         91
Vistara     5.368328        100

In [61]:
cancellation_by_airline = df.groupby("Airline").agg(
    Total_Flights=("Flight_ID", "nunique"),
    Cancelled_Flights=("Cancellation_Status", lambda x: (x == "Cancelled").sum())
)

cancellation_by_airline["Cancellation_Rate_%"] = (
    cancellation_by_airline["Cancelled_Flights"]
    / cancellation_by_airline["Total_Flights"] * 100
).round(2)

cancellation_by_airline.sort_values("Cancellation_Rate_%", ascending=False)

           Total_Flights  Cancelled_Flights  Cancellation_Rate_%
Airline
IndiGo              6596                516                 7.82
Vistara             4153                251                 6.04
Air India           4911                291                 5.93
SpiceJet            3496                195                 5.58
Go First            2683                145                 5.40
Akasa Air           2394                115                 4.80

In [62]:
flight_status_by_airline = pd.crosstab(
    df["Airline"],
    df["Flight_Status"]
)

flight_status_by_airline

Flight_Status  Cancelled  Delayed  On Time
Airline
Air India            291     1051     5730
Akasa Air            115      438     2194
Go First             145      476     2556
IndiGo               516     1740     9595
SpiceJet             195      653     3601
Vistara              251      824     4564

In [63]:
route_analysis = df.groupby(
    ["Origin_Airport", "Destination_Airport"]
).agg(
    Passengers=("Passenger_ID", "nunique"),
    Flights=("Flight_ID", "nunique"),
    Revenue=("Ticket_Fare", "sum")
).sort_values("Passengers", ascending=False)

route_analysis.head(10)

                                    Passengers  Flights   Revenue
Origin_Airport Destination_Airport
BOM            JAI                         439      426  790200.0
GOI            CCU                         433      429  779400.0
HYD            CCU                         432      423  777600.0
GOI            HYD                         422      411  759600.0
PNQ            CCU                         421      410  759600.0
BOM            CCU                         421      411  757800.0
PNQ            HYD                         419      411  754200.0
HYD            MAA                         413      400  743400.0
JAI            GOI                         413      408  743400.0
HYD            BLR                         411      399  739800.0

In [64]:
delay_satisfaction = df.groupby("Passenger_Satisfaction").agg(
    Avg_Delay=("Delay_Minutes", "mean"),
    Passengers=("Passenger_ID", "nunique")
).sort_index()

delay_satisfaction

                        Avg_Delay  Passengers
Passenger_Satisfaction
1                        0.000000         860
2                        2.603774         635
3                        8.433025        4330
4                        5.928123       17514
5                        4.168032       11591